### PR TITLE
JIRA:CBS-235 requirement file is missing for lunrdriver

### PR DESCRIPTION
**Pull request by PythonGirlSam**
Added test-requirement.txt file for resolving ticket 
https://jira.rax.io/browse/CBS-233

### CODE REVIEW

**Comment by PythonGirlSam** [comment]
Bug tracker issue check failed: No existing tracker issues found in any commit message

For more details, see: http://10.127.1.169:8080/jenkins/job/process_github_pr_lunrdriver/17/consoleFull

**Comment by SaumyaRackspace** [comment]
Could not find the following issues:

* jira
  * JIRA:CBS-235

**Comment by PythonGirlSam** [comment]
Triggering unit tests...

**Comment by PythonGirlSam** [comment]
Running tests with './.unittests'...

For more details, see: http://10.127.1.169:8080/jenkins/job/test-lunrdriver-change/15/consoleFull

{{{test:started:15}}}

**Comment by PythonGirlSam** [comment]
Test suite failed: './.unittests' failed with return code 1

For more details, see: http://10.127.1.169:8080/jenkins/job/test-lunrdriver-change/15/consoleFull

{{{test:complete}}}

**Comment by PythonGirlSam** [comment]
Bug tracker issue check failed: No existing tracker issues found in any commit message

For more details, see: http://10.127.1.169:8080/jenkins/job/process_github_pr_lunrdriver/18/consoleFull

**Comment by PythonGirlSam** [comment]
Could not find the following issues:

* jira
  * JIRA:CBS-235

**Comment by PythonGirlSam** [comment]
Running tests with './.unittests'...

For more details, see: http://10.127.1.169:8080/jenkins/job/test-lunrdriver-change/16/consoleFull

{{{test:started:16}}}

**Comment by PythonGirlSam** [comment]
Triggering unit tests...

**Comment by PythonGirlSam** [comment]
Test suite failed: './.unittests' failed with return code 1

For more details, see: http://10.127.1.169:8080/jenkins/job/test-lunrdriver-change/16/consoleFull

{{{test:complete}}}

**Comment by PythonGirlSam** [comment]
Bug tracker issue check failed: No existing tracker issues found in any commit message

For more details, see: http://10.127.1.169:8080/jenkins/job/process_github_pr_lunrdriver/19/consoleFull

**Comment by PythonGirlSam** [comment]
Could not find the following issues:

* jira
  * JIRA:CBS-235

**Comment by PythonGirlSam** [comment]
Triggering unit tests...

**Comment by PythonGirlSam** [comment]
Running tests with './.unittests'...

For more details, see: http://10.127.1.169:8080/jenkins/job/test-lunrdriver-change/17/consoleFull

{{{test:started:17}}}

**Comment by PythonGirlSam** [comment]
Test suite failed: './.unittests' failed with return code 1

For more details, see: http://10.127.1.169:8080/jenkins/job/test-lunrdriver-change/17/consoleFull

{{{test:complete}}}

**Comment by PythonGirlSam** [comment]
Bug tracker issue check failed: No existing tracker issues found in any commit message

For more details, see: http://10.127.1.169:8080/jenkins/job/process_github_pr_lunrdriver/20/consoleFull

**Comment by PythonGirlSam** [comment]
Could not find the following issues:

* jira
  * JIRA:CBS-235

**Comment by PythonGirlSam** [comment]
Triggering unit tests...

**Comment by PythonGirlSam** [comment]
Running tests with './.unittests'...

For more details, see: http://10.127.1.169:8080/jenkins/job/test-lunrdriver-change/18/consoleFull

{{{test:started:18}}}

**Comment by PythonGirlSam** [comment]
Test suite failed: './.unittests' failed with return code 1

For more details, see: http://10.127.1.169:8080/jenkins/job/test-lunrdriver-change/18/consoleFull

{{{test:complete}}}

**Comment by PythonGirlSam** [comment]
Running tests with './.unittests'...

For more details, see: http://10.127.1.169:8080/jenkins/job/test-lunrdriver-change/19/consoleFull

{{{test:started:19}}}

**Comment by PythonGirlSam** [comment]
Test suite passed!

For more details, see: http://10.127.1.169:8080/jenkins/job/test-lunrdriver-change/19/consoleFull

{{{test:complete}}}

**Comment by PythonGirlSam** [comment]
Running tests with './.unittests'...

For more details, see: http://10.127.1.169:8080/jenkins/job/test-lunrdriver-change/20/consoleFull

{{{test:started:20}}}

**Comment by SaumyaRackspace** [comment]
Test suite failed: './.unittests' failed with return code 1

For more details, see: http://10.127.1.169:8080/jenkins/job/test-lunrdriver-change/20/consoleFull

{{{test:complete}}}

**Comment by PythonGirlSam** [comment]
Running tests with './.unittests'...

For more details, see: http://10.127.1.169:8080/jenkins/job/test-lunrdriver-change/21/consoleFull

{{{test:started:21}}}

**Comment by PythonGirlSam** [comment]
Test suite passed!

For more details, see: http://10.127.1.169:8080/jenkins/job/test-lunrdriver-change/21/consoleFull

{{{test:complete}}}

**Comment by PythonGirlSam** [comment]
Running tests with './.unittests'...

For more details, see: http://10.127.1.169:8080/jenkins/job/test-lunrdriver-change/22/consoleFull

{{{test:started:22}}}

**Comment by PythonGirlSam** [comment]
Test suite passed!

For more details, see: http://10.127.1.169:8080/jenkins/job/test-lunrdriver-change/22/consoleFull

{{{test:complete}}}

**Pull request closed without merging**
